kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-local
  namespace: antipilug
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-pv-mongodb
  storageClassName: local
  volumeMode: Filesystem
