apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
